services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 #Poll every 60 seconds
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    

  app:
    image: ctechasiri/express-app:latest
    ports:
      - "8080:8080"
